version: "3.0"
services:
  api:
    image: hazzikostas_api
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - TZ=Europe/Madrid
    networks:
      - proxy
    container_name: hazzikostas_api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.hazzikostas-api-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.hazzikostas-api-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.hazzikostas-api-web.middlewares=hazzikostas-api-redirect-websecure"
      - traefik.http.routers.hazzikostas-api-web.rule=Host(`hazzikostas.thexiao77.xyz`)
      - traefik.http.routers.hazzikostas-api-web.entrypoints=web
      - traefik.http.routers.hazzikostas-api-websecure.rule=Host(`hazzikostas.thexiao77.xyz`)
      - traefik.http.routers.hazzikostas-api-websecure.tls.certresolver=le
      - traefik.http.routers.hazzikostas-api-websecure.tls=true
      - traefik.http.routers.hazzikostas-api-websecure.entrypoints=web-secured
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
